/**
 * Example: Custom JSON source
 *
 * This file shows how to implement WritableEnvSource to load and persist
 * env variables from a JSON file instead of a .env file.
 *
 * The source:
 *   - load()  → reads env.json and returns a flat key→value map
 *   - write() → receives the full WritePayload (field metadata + values)
 *               and writes a structured, annotated JSON file
 *
 * Use this as a starting point for any custom backend:
 *   AWS SSM, HashiCorp Vault, Redis, a remote API, etc.
 */

import { readFileSync, writeFileSync, existsSync } from 'fs'
import { resolve } from 'path'
import { defineEnv, LocalEnvSource } from 'envkit-core'
import type { WritableEnvSource, WritePayload, EnvFieldDef, PlainEnvFieldDef } from 'envkit-core'

// ── Custom source implementation ──────────────────────────────────────────────

interface JsonEnvFile {
  $schema?: string
  $comment?: string
  vars: Record<string, {
    value: string | null
    description?: string
    required?: boolean
    secret?: boolean
  }>
}

function jsonSource(options: { path?: string } = {}): WritableEnvSource {
  const filePath = options.path ?? 'env.json'

  return {
    filePath,

    load(cwd = process.cwd()): Record<string, string> {
      const abs = resolve(cwd, filePath)
      if (!existsSync(abs)) return {}

      const raw: JsonEnvFile = JSON.parse(readFileSync(abs, 'utf-8'))
      const out: Record<string, string> = {}

      for (const [key, entry] of Object.entries(raw.vars ?? {})) {
        if (entry.value !== null && entry.value !== undefined) {
          out[key] = String(entry.value)
        }
      }

      return out
    },

    write(payload: WritePayload, cwd = process.cwd()): void {
      // In generate mode write to env.example.json (or --output override), not the live file
      const target = payload.outputPath
        ?? (payload.mode === 'generate' ? filePath.replace(/(\.\w+)$/, '.example$1') : filePath)
      const abs = resolve(cwd, target)

      const vars: JsonEnvFile['vars'] = {}

      // Preserve group ordering — iterate groups first, then ungrouped
      const grouped = new Map<string, string[]>()
      const ungrouped: string[] = []

      for (const [key, field] of Object.entries(payload.envs)) {
        const slug = (field as PlainEnvFieldDef<string>).group
        if (slug) {
          if (!grouped.has(slug)) grouped.set(slug, [])
          grouped.get(slug)!.push(key)
        } else {
          ungrouped.push(key)
        }
      }

      const orderedKeys: string[] = []
      for (const group of payload.groups) {
        orderedKeys.push(...(grouped.get(group.slug) ?? []))
      }
      orderedKeys.push(...ungrouped)

      for (const key of orderedKeys) {
        const field = payload.envs[key]!
        const plain = field as PlainEnvFieldDef<string>
        vars[key] = {
          value: field.value,
          description: field.description,
          ...(plain.required !== undefined && { required: plain.required }),
          ...(plain.secret && { secret: true }),
        }
      }

      const out: JsonEnvFile = {
        $comment: 'Generated by envkit — do not commit secrets to version control',
        vars,
      }

      writeFileSync(abs, JSON.stringify(out, null, 2) + '\n', 'utf-8')
    },
  }
}

// ── Config ────────────────────────────────────────────────────────────────────

export default defineEnv({
  source: jsonSource({ path: 'env.json' }),

  envGroups: [
    { slug: 'server',   name: 'Server',        description: 'HTTP server settings' },
    { slug: 'database', name: 'Database',       description: 'Database connection' },
    { slug: 'auth',     name: 'Authentication', description: 'Auth secrets' },
  ],

  envSchema: {
    NODE_ENV: {
      type: ['development', 'staging', 'production'] as const,
      default: 'development',
      description: 'Application runtime environment',
      group: 'server',
      required: true,
    },
    PORT: {
      type: 'number',
      default: 3000,
      description: 'HTTP server port',
      howToGet: 'Pick any free port on your machine',
      group: 'server',
      required: false,
      min: 1,
      max: 65535,
    },
    DATABASE_URL: {
      type: 'url',
      description: 'PostgreSQL connection string',
      howToGet: 'Get from your DB provider or run: docker compose up db',
      group: 'database',
      required: true,
      example: 'postgresql://user:pass@localhost:5432/myapp',
    },
    JWT_SECRET: {
      type: 'string',
      description: 'Secret key for signing JWT tokens',
      howToGet: 'Generate with: openssl rand -hex 64',
      group: 'auth',
      required: true,
      secret: true,
      minLength: 32,
    },
  },

  computed: {
    IS_PRODUCTION: {
      description: 'True when running in production mode',
      compute: ({ env }) => env.NODE_ENV === 'production',
    },
  },
})
